In [3]:
import numpy as np

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


In [4]:
np.__version__

'2.5.1'

## Create & Read

### 1D Array

In [5]:
arr1 = np.array([1,2,3,4,5,6])

In [6]:
arr1

array([1, 2, 3, 4, 5, 6])

In [7]:
type(arr1)

numpy.ndarray

In [8]:
arr1.shape

(6,)

In [9]:
arr1.dtype

dtype('int64')

In [10]:
arr1.ndim

1

In [11]:
arr1.size

6

### 2D Array

In [12]:
arr2 = np.array([[1,4,5],[6,7,4]])

In [14]:
arr2


array([[1, 4, 5],
       [6, 7, 4]])

In [15]:
arr2.ndim

2

In [16]:
arr2.shape #(row,col)

(2, 3)

In [17]:
arr2.dtype

dtype('int64')

In [18]:
arr2.size

6

### 3D Array

In [22]:
arr3 = np.array([[[1,4,5],[6,7,4]], [[3,4,5],[9,8,7]],[[1,4,5],[6,7,4]]])

In [23]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 4, 5],
        [9, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [24]:
arr3.ndim

3

In [25]:
arr3.shape

(3, 2, 3)

In [26]:
arr3.size

18

### Create random array

In [27]:
randomArr = np.random.rand(3,2,3)

In [28]:
randomArr

array([[[0.5267364 , 0.70700182, 0.78003241],
        [0.02580115, 0.24127894, 0.30462236]],

       [[0.34953872, 0.80127111, 0.28182385],
        [0.93304082, 0.85205578, 0.65449351]],

       [[0.24039487, 0.54527216, 0.6706656 ],
        [0.67336053, 0.19938765, 0.36363325]]])

In [29]:
randomArr.dtype

dtype('float64')

In [30]:
zeroes = np.zeros((3,2,3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [31]:
zeroes.ndim

3

In [34]:
full = np.full((3,2,3),9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [35]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 4, 5],
        [9, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [39]:
arr3[0][0][1]

np.int64(4)

### Update & Delete

In [40]:
a1 = np.random.rand(2,3,2)
a2 = np.random.rand(2,3,2)

In [41]:
a1

array([[[0.74245862, 0.76195933],
        [0.93696784, 0.69188718],
        [0.55901416, 0.32192841]],

       [[0.14973254, 0.43546988],
        [0.68270382, 0.13432767],
        [0.11124581, 0.80115892]]])

In [42]:
a2

array([[[0.90318837, 0.73342512],
        [0.39765349, 0.04854088],
        [0.56762618, 0.26702653]],

       [[0.35900745, 0.01130486],
        [0.12899601, 0.35655188],
        [0.99704649, 0.06995781]]])

### Basic Math Operations

In [43]:
np.add(a1,a2)

array([[[1.64564699, 1.49538445],
        [1.33462133, 0.74042806],
        [1.12664034, 0.58895494]],

       [[0.50873999, 0.44677474],
        [0.81169983, 0.49087956],
        [1.1082923 , 0.87111674]]])